defaults:
  - colorlog


formatters:
  colorlog:
    (): colorlog.ColoredFormatter
    datefmt: '%m-%d %H:%M:%S'
    format: '%(green)s%(asctime)s%(reset)s %(blue)s%(name)s %(process)d%(reset)s %(log_color)s%(message)s'
    log_colors:
      DEBUG: cyan
      INFO: black
      WARNING: yellow
      ERROR: red
      CRITICAL: red
        

disable_existing_loggers: false